alpaca:
  api:
    key: "PKHS35UZWYTOKDGZMAKV"
    secret: "VZ0MyT6lhgsBaeeSOKGyNEWzfwa1KfASG3wZfGKF"
  base:
    url: "https://paper-api.alpaca.markets/v2"

#account username and pwd = gemon67807@ofionk.com