alpaca:
  api:
    key: "PKJ39KC6D6TF1JB3YJYE"
    secret: "iWeOjR1jlfzwhPKuEaHh43v0nKlqRgXbHJPPyYjc"
  base:
    url: "https://paper-api.alpaca.markets/v2"
  data:
    url: "https://data.alpaca.markets"




#account username and pwd = gemon67807@ofionk.com